[workspace]
default-members = ["connectorx"]
members = ["connectorx", "connectorx-cpp"]

[profile.release]
debug = true
lto = true

[workspace.dependencies]
arrow2 = {version = "0.17", default-features = false}
