[workspace]
default-members = ["connectorx"]
members = ["connectorx", "connectorx-cpp"]
resolver = "2"

[profile.release]
debug = true
lto = true

[workspace.dependencies]
arrow = {version = "49", features = ["prettyprint", "ffi"]}
arrow2 = {version = "0.17", default-features = false}
